# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    
    runs-on: linux
    steps:

      - name: 1.0 cleanup
        uses: AutoModality/action-clean@v1
    
      - name: 1.1 setup cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
            
      - name: 2.0 checkout
        uses: actions/checkout@v2
      
      - name: 3.0 yarn install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install --frozen-lockfile
          
      - name: 3.1 yarn build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - name: 4.0 docker build image
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: 4.1 create time tag
        run: echo "TIME_VERSION_TAG=$(date +'%Y').$(( `date +'%m'`/6+1 ))" >> $GITHUB_ENV
      
      - name: 4.2 login docker-hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: 4.3 build-push to docker-hub
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/english-flashcard-ui:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/english-flashcard-ui:${{env.TIME_VERSION_TAG}}
